[workspace]
members = [
    "collections",
    "system",
    "kernel",
    "usrlib",
    "arch/x86_64",
    "arch/x86_32",
    "apps/shell",
    "apps/dummy",
    "apps/hello_elf",
    "apps/random_gen_server",
    "apps/snake",
    "apps/tetris",
    "apps/conway",
    "apps/test_suite",
    "xtask",
]
default-members = [
    "collections",
    "system",
    "kernel",
    "usrlib",
    "apps/shell",
    "apps/dummy",
    "apps/test_suite",
    "xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = 2
