[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "random_gen_server"
publish = false
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "random_gen_server"
bench = false
test = false

[dependencies]
system = { path = "../../system" }
usrlib = { path = "../../usrlib" }
